#!/bin/bash

set -e

this_ip="$1"
this_machine="$2"

etcdctl="docker run --net=host --rm quay.io/pingles/etcdctl:latest"
fleetctl="docker run --net=host --rm cap10morgan/fleetctl:v0.8.3"

bootstrap_expect=$(${fleetctl} list-machines | grep -v IP | wc -l)

echo "expecting ${bootstrap_expect} machines"

echo "setting /consul.io/bootstrap/machines/${this_machine} ${this_ip}"
${etcdctl} set /consul.io/bootstrap/machines/${this_machine} ${this_ip}

nodes=( $(${etcdctl} ls /consul.io/bootstrap/machines) )
first_node=${nodes[0]}

echo "first_node ${first_node}"

if [[ -n "${first_node}" ]]; then
  join_ip=$(${etcdctl} get ${first_node})
  if [[ "${join_ip}" == "${this_ip}" ]]; then
    join_ip=""
  fi
fi
echo "joining ${join_ip}"

ip_args="${this_ip}"
if [[ -n "${join_ip}" ]]; then
  ip_args="${ip_args}::${join_ip}"
fi

printf -v cmd '$(docker run --rm progrium/consul cmd:run %s -v /var/lib/consul:/data)' "${ip_args}"

echo "pulling progrium/consul"
docker pull progrium/consul

echo "starting consul docker: ${cmd}"
exec /bin/bash -c "${cmd}"
