#!/bin/bash

machine_id="$1"
listen_ip="$2"

echo "starting consul on machine $machine_id, local ip $listen_ip"

docker_host_ip=$(netstat -nr | grep '^0\.0\.0\.0' | awk '{print $2}')
echo "docker host ip: $docker_host_ip"

echo "bootstrapping with etcd"
etcdctl="etcdctl --peers http://$docker_host_ip:4001"
echo "setting /consul.io/bootstrap/machines/$machine_id to $listen_ip for bootstrap"
${etcdctl} set "/consul.io/bootstrap/machines/$machine_id" $listen_ip > /dev/null

run_mode=""
echo "listing other bootstrap machines"
for node_path in $(${etcdctl} ls /consul.io/bootstrap/machines); do
  join_ip=$( ${etcdctl} get $node_path --consistent )
  
  if [[ "${join_ip}" != "${listen_ip}" ]]; then
    echo "will join with ${join_ip}"
    run_mode="-join $join_ip"
  fi
done

shift
shift

echo "starting consul: agent, -server, -config-dir=/config, -data-dir=/data, -ui-dir=/ui, -bootstrap-expect 3 $run_mode $@"
/bin/consul agent -server -config-dir=/config -data-dir=/data -ui-dir=/ui -bootstrap-expect 3 $run_mode $@
